/**
 * Boot-time (idempotent) migration runner.
 *
 * Uses the migrations generated by `drizzle-kit` in /drizzle. Drizzle tracks
 * applied migrations in a `__drizzle_migrations` meta table, making this
 * naturally idempotent. Called from both the web process (on module load, via
 * a lazily-invoked helper) and the engine process (on start).
 */

import fs from "node:fs";
import path from "node:path";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate as drizzleMigrate } from "drizzle-orm/better-sqlite3/migrator";
import { getRawDb } from "./index";

/** Locate the migrations folder (project-root /drizzle). */
function migrationsFolder(): string {
  const candidates = [
    path.resolve(process.cwd(), "drizzle"),
    // When executed from a nested cwd (e.g. via tsx from engine/), walk up.
    path.resolve(__dirname, "../../../../drizzle"),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  throw new Error(
    "Could not locate drizzle migrations folder. Run `npm run db:generate` first.",
  );
}

/**
 * Apply any pending migrations. Idempotent — safe to call on every boot.
 */
export function migrate(dbPath?: string): void {
  const db = getRawDb(dbPath);
  const migrator = drizzle(db);
  const folder = migrationsFolder();
  drizzleMigrate(migrator, { migrationsFolder: folder });
}
