/**
 * Boot-time (idempotent) migration runner.
 *
 * Uses the migrations generated by `drizzle-kit` in /drizzle. Drizzle tracks
 * applied migrations in a `__drizzle_migrations` meta table, making this
 * naturally idempotent. Called from both the web process (on module load, via
 * a lazily-invoked helper) and the engine process (on start).
 *
 * FK-safety: drizzle's migrator wraps ALL migration statements — including the
 * table-rebuild DROPs that CHECK-alter migrations emit (0001, 0004) — in a
 * single `BEGIN…COMMIT`. SQLite forbids changing the `foreign_keys` pragma
 * inside a transaction, so a `PRAGMA foreign_keys=OFF;` embedded inside a
 * migration file is a NO-OP under drizzle: FKs stay ON, and `DROP TABLE`
 * (parent) then CASCADEs into every referencing child (agent_messages,
 * approval_requests, artifacts, usage_records, notifications, execution_events,
 * subtasks, handoffs) — wiping real execution history on upgrade.
 *
 * To keep rebuild migrations non-destructive we disable FK enforcement on the
 * raw connection BEFORE calling the migrator (the pragma is per-connection and
 * cannot change mid-transaction, so it must be set ahead of the migrator's own
 * BEGIN). After the migrator commits we restore `foreign_keys=ON` and run
 * `PRAGMA foreign_key_check` as a safety net. This is the general guarantee and
 * covers every rebuild migration (including 0001, which has the same latent
 * OFF/ON pattern that was previously a no-op under drizzle).
 *
 * Phase 6 note: migrations 0005 (audit_log) and 0006 are ADDITIVE ONLY
 * (CREATE TABLE / ALTER TABLE ADD COLUMN) and intentionally emit NO in-file
 * `PRAGMA foreign_keys` toggle — such toggles are no-ops inside the migrator's
 * single transaction. If a future migration must rebuild a CHECK-constrained
 * table, rely on the FK-off guard here and add a regression test; do not add a
 * PRAGMA to the .sql file.
 */

import fs from "node:fs";
import path from "node:path";
import type Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate as drizzleMigrate } from "drizzle-orm/better-sqlite3/migrator";
import { getRawDb } from "./index";

/** Locate the migrations folder (project-root /drizzle). */
function migrationsFolder(): string {
  const candidates = [
    path.resolve(process.cwd(), "drizzle"),
    // When executed from a nested cwd (e.g. via tsx from engine/), walk up.
    path.resolve(__dirname, "../../../../drizzle"),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  throw new Error(
    "Could not locate drizzle migrations folder. Run `npm run db:generate` first.",
  );
}

/**
 * Apply any pending migrations. Idempotent — safe to call on every boot.
 *
 * See the module docblock for why `foreign_keys` must be disabled around the
 * migrator's self-managed transaction. After a successful migrate we restore
 * FK enforcement and assert no foreign-key relationship was invalidated by a
 * rebuild (each child survives because the FK cascade was disabled, but a
 * rebuild that leaves a dangling reference is still an error).
 */
export function migrate(dbPath?: string): void {
  const db = getRawDb(dbPath);
  // PRAGMA foreign_keys is per-connection and CANNOT be changed mid-transaction;
  // disable it now so it stays OFF through the migrator's own BEGIN…COMMIT.
  db.pragma("foreign_keys = OFF");
  try {
    const migrator = drizzle(db);
    const folder = migrationsFolder();
    drizzleMigrate(migrator, { migrationsFolder: folder });
  } finally {
    // Restore the production FK-enforcing mode that getRawDb established at
    // connection time, regardless of whether a migration succeeded.
    db.pragma("foreign_keys = ON");
  }
  // Safety net: assert no rebuild left a violation. Only valid to run outside a
  // transaction with FK enforcement enabled.
  const violations = db.pragma("foreign_key_check") as unknown as unknown[];
  if (violations.length > 0) {
    throw new Error(
      `migrate: foreign key check failed after migration (${violations.length} violation(s))`,
    );
  }
}
